project:
  type: website
  output-dir: docs

website:
  title: "Learning Security - Cloud Security"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - azure-cloud-security.qmd
      - google-cloud-security.qmd
  sidebar:
    - title: "Home"
      style: "docked"
      background: light
      contents:
        - text: "---"
        - section: Cloud Security
        - text: "---"
        - azure-cloud-security.qmd
        - text: "---"
        - section: Foo
        - text: "---"
        - azure-cloud-security/foo-1.qmd
        - azure-cloud-security/foo-2.qmd
        - azure-cloud-security/foo-3.qmd
        - text: "---"
        - google-cloud-security.qmd    
        - text: "---"
        - section: Bar
        - text: "---"
        - google-cloud-security/bar-1.qmd
        - google-cloud-security/bar-2.qmd
        - google-cloud-security/bar-3.qmd    
    - title: "Azure Cloud Security"
      style: "docked"
      background: light
      contents:
        - text: "---"
        - section: Azure Cloud Security
        - text: "---"
        - azure-cloud-security.qmd
        - text: "---"
        - section: Foo
        - text: "---"
        - azure-cloud-security/foo-1.qmd
        - azure-cloud-security/foo-2.qmd
        - azure-cloud-security/foo-2.qmd 
    - title: "Google Cloud Security"
      style: "docked"
      background: light
      contents:
        - text: "---"
        - section: Google Cloud Security
        - text: "---"
        - google-cloud-security.qmd
        - text: "---"
        - section: Bar
        - text: "---"
        - google-cloud-security/bar-1.qmd
        - google-cloud-security/bar-2.qmd
        - google-cloud-security/bar-2.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
